#!/bin/bash

for f in *; do
    if [ -d "$f" ]; then
        # $f is a directory
        cd "$f"
	echo "$f"
        ls
	for f in *:*; do mv -v "$f" $(echo "$f" | tr ':' '-'); done
	ls
        cd ..
    fi
done